#!/bin/sh

case "$1" in
	start)
		printf "Starting connman ... "
		#ip -f inet neigh
		#ip -f inet addr 
		start-stop-daemon -S -q -m -p /var/run/connmand.pid --exec /usr/sbin/connmand -- -I `ip -f inet r | cut -d ' ' -f 3`
		echo "done."
		;;
	stop)
		printf "Stopping connman ..."
		start-stop-daemon -K -q -p /var/run/connmand.pid
		echo "done."
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	*)
		echo "usage: $0 {start|stop|restart}"
		;;
esac

